In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings("ignore")


In [2]:

df=pd.read_excel("Job_Scheduling.xlsx")
df.head()


Job Id  Burst time  Arrival Time  Preemptive  Resources
0     334       179.0        0.6875         1.0        4.0
1     234       340.0        0.7800         0.0        4.0
2     138       143.0        0.9150         1.0        4.0
3     463       264.0           NaN         0.0        5.0
4     283       216.0        0.5550         0.0        6.0

In [3]:
df.tail()

Job Id  Burst time  Arrival Time  Preemptive  Resources
14     163       103.0        0.4600         0.0        5.0
15     453       213.0        0.0775         1.0        1.0
16     176       251.0        0.7050         0.0        6.0
17     449        49.0        0.2550         1.0        4.0
18      11       168.0        0.3175         1.0        7.0

In [4]:
x=df.iloc[:,0:4].values#extracting all columns from 0-4 ()
print(x)

[[3.340e+02 1.790e+02 6.875e-01 1.000e+00]
 [2.340e+02 3.400e+02 7.800e-01 0.000e+00]
 [1.380e+02 1.430e+02 9.150e-01 1.000e+00]
 [4.630e+02 2.640e+02       nan 0.000e+00]
 [2.830e+02 2.160e+02 5.550e-01 0.000e+00]
 [8.800e+01 3.600e+01 6.625e-01 0.000e+00]
 [3.960e+02 1.280e+02 1.975e-01 1.000e+00]
 [4.700e+02 2.030e+02 9.875e-01 1.000e+00]
 [3.350e+02 2.710e+02 2.750e-02 0.000e+00]
 [2.720e+02 3.990e+02 2.150e-01       nan]
 [2.370e+02       nan 4.825e-01 1.000e+00]
 [3.180e+02 3.110e+02 5.675e-01 1.000e+00]
 [8.400e+01 1.110e+02 2.725e-01 1.000e+00]
 [3.110e+02 8.700e+01       nan 0.000e+00]
 [1.630e+02 1.030e+02 4.600e-01 0.000e+00]
 [4.530e+02 2.130e+02 7.750e-02 1.000e+00]
 [1.760e+02 2.510e+02 7.050e-01 0.000e+00]
 [4.490e+02 4.900e+01 2.550e-01 1.000e+00]
 [1.100e+01 1.680e+02 3.175e-01 1.000e+00]]


In [5]:
df.isnull().sum()

Job Id          0
Burst time      1
Arrival Time    2
Preemptive      1
Resources       1
dtype: int64

In [6]:
y=df.iloc[:,4].values
print(y)

[ 4.  4.  4.  5.  6.  5. nan  4.  3.  3.  4.  1.  2.  7.  5.  1.  6.  4.
  7.]


In [7]:
#Data Cleaning
#1) Dealing with missing values 
#Filling means values by (mean) Methods
from sklearn.impute import SimpleImputer
imp=SimpleImputer(missing_values=np.nan,strategy='mean')
X=imp.fit_transform(x) #here fit_transform kiya kerayga phalay yaa fit keraygaa saray parameter koo or phir jo parameter fit hoya hai unkoo transform keraygaa
print(X)

[[3.34000000e+02 1.79000000e+02 6.87500000e-01 1.00000000e+00]
 [2.34000000e+02 3.40000000e+02 7.80000000e-01 0.00000000e+00]
 [1.38000000e+02 1.43000000e+02 9.15000000e-01 1.00000000e+00]
 [4.63000000e+02 2.64000000e+02 4.80294118e-01 0.00000000e+00]
 [2.83000000e+02 2.16000000e+02 5.55000000e-01 0.00000000e+00]
 [8.80000000e+01 3.60000000e+01 6.62500000e-01 0.00000000e+00]
 [3.96000000e+02 1.28000000e+02 1.97500000e-01 1.00000000e+00]
 [4.70000000e+02 2.03000000e+02 9.87500000e-01 1.00000000e+00]
 [3.35000000e+02 2.71000000e+02 2.75000000e-02 0.00000000e+00]
 [2.72000000e+02 3.99000000e+02 2.15000000e-01 5.55555556e-01]
 [2.37000000e+02 1.92888889e+02 4.82500000e-01 1.00000000e+00]
 [3.18000000e+02 3.11000000e+02 5.67500000e-01 1.00000000e+00]
 [8.40000000e+01 1.11000000e+02 2.72500000e-01 1.00000000e+00]
 [3.11000000e+02 8.70000000e+01 4.80294118e-01 0.00000000e+00]
 [1.63000000e+02 1.03000000e+02 4.60000000e-01 0.00000000e+00]
 [4.53000000e+02 2.13000000e+02 7.75000000e-02 1.000000

In [8]:
from sklearn.impute import SimpleImputer
imp=SimpleImputer(missing_values=np.nan,strategy='mean')
Y=y.reshape(-1,1)# CONVERT into 2_d array
Y=imp.fit_transform(Y) #here fit_transform kiya kerayga phalay yaa fit keraygaa saray parameter koo or phir jo parameter fit hoya hai unkoo transform keraygaa
print(Y)

[[4.        ]
 [4.        ]
 [4.        ]
 [5.        ]
 [6.        ]
 [5.        ]
 [4.16666667]
 [4.        ]
 [3.        ]
 [3.        ]
 [4.        ]
 [1.        ]
 [2.        ]
 [7.        ]
 [5.        ]
 [1.        ]
 [6.        ]
 [4.        ]
 [7.        ]]


In [9]:
Y=y.reshape(-1)#convert again into 1-D array
print(Y)


[ 4.  4.  4.  5.  6.  5. nan  4.  3.  3.  4.  1.  2.  7.  5.  1.  6.  4.
  7.]


In [10]:

#The SimpleImputer class also supports categorical data represented as string values or pandas 
#categoricals when using the 'most_frequent' or 'constant' strategy:
df1=pd.DataFrame([["a","b"],[np.nan,"y"],["a",np.nan],["b","y"]],dtype="category")
df1


0    1
0    a    b
1  NaN    y
2    a  NaN
3    b    y

In [11]:
#here one thing we know that we k ki value odd humaesha binary classification may hoogii

#2) Rescaling the Variable 
# Rescaling and variable hum zadiya thur un model may kertay haii jahan difference liya jaraha hoo
#jesay KNN may Distance lay rahy hootay haii 


#rescaling Burst Time :
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler(feature_range=(0,1))
rescaledX=scaler.fit_transform(X[:,1].reshape(-1,1))
np.set_printoptions(precision=3)# DECIMAL VALUES KO SET KER RAHA HAI KIINI DECIMAL VALUES CHAIYA 
X[:,1]=rescaledX.reshape(1,-1)
print(X[:,1])


[0.394 0.837 0.295 0.628 0.496 0.    0.253 0.46  0.647 1.    0.432 0.758
 0.207 0.14  0.185 0.488 0.592 0.036 0.364]


In [12]:
#Normalizing data
from sklearn.preprocessing import Normalizer
scaler=Normalizer().fit(X)
normalizedX=scaler.transform(X)
normalizedX

array([[1.000e+00, 1.179e-03, 2.058e-03, 2.994e-03],
       [1.000e+00, 3.579e-03, 3.333e-03, 0.000e+00],
       [9.999e-01, 2.136e-03, 6.630e-03, 7.246e-03],
       [1.000e+00, 1.357e-03, 1.037e-03, 0.000e+00],
       [1.000e+00, 1.752e-03, 1.961e-03, 0.000e+00],
       [1.000e+00, 0.000e+00, 7.528e-03, 0.000e+00],
       [1.000e+00, 6.400e-04, 4.987e-04, 2.525e-03],
       [1.000e+00, 9.788e-04, 2.101e-03, 2.128e-03],
       [1.000e+00, 1.932e-03, 8.209e-05, 0.000e+00],
       [1.000e+00, 3.676e-03, 7.904e-04, 2.042e-03],
       [1.000e+00, 1.824e-03, 2.036e-03, 4.219e-03],
       [1.000e+00, 2.382e-03, 1.785e-03, 3.145e-03],
       [9.999e-01, 2.459e-03, 3.244e-03, 1.190e-02],
       [1.000e+00, 4.518e-04, 1.544e-03, 0.000e+00],
       [1.000e+00, 1.132e-03, 2.822e-03, 0.000e+00],
       [1.000e+00, 1.076e-03, 1.711e-04, 2.207e-03],
       [1.000e+00, 3.365e-03, 4.006e-03, 0.000e+00],
       [1.000e+00, 7.976e-05, 5.679e-04, 2.227e-03],
       [9.949e-01, 3.289e-02, 2.872e-02, 9.045

In [13]:
# another data set 
WD=pd.read_excel("weatherTemp.xlsx")
WD.head()

weather temperature play
0     sunny         hot   no
1     sunny         hot   no
2  overcast         hot  yes
3     rainy        mild  yes
4     rainy        cool  yes

In [14]:
WD.tail()

weather temperature play
9      rainy        mild  yes
10     sunny        mild  yes
11  overcast        mild  yes
12  overcast         hot  yes
13     rainy        mild   no

In [15]:
WD.describe()


weather temperature play
count       14          14   14
unique       3           3    2
top      sunny        mild  yes
freq         5           6    9

In [16]:
WD.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   weather      14 non-null     object
 1   temperature  14 non-null     object
 2   play         14 non-null     object
dtypes: object(3)
memory usage: 464.0+ bytes


In [17]:
#Checking the Null Values
WD.isnull().sum()

weather        0
temperature    0
play           0
dtype: int64

In [18]:
#Independent and Dependent Variable
x=WD.iloc[:,0:2].values
print(x)

[['sunny' 'hot']
 ['sunny' 'hot']
 ['overcast' 'hot']
 ['rainy' 'mild']
 ['rainy' 'cool']
 ['rainy' 'cool']
 ['overcast' 'cool']
 ['sunny' 'mild']
 ['sunny' 'cool']
 ['rainy' 'mild']
 ['sunny' 'mild']
 ['overcast' 'mild']
 ['overcast' 'hot']
 ['rainy' 'mild']]


In [19]:
y=WD.iloc[:,2].values
print(y)


['no' 'no' 'yes' 'yes' 'yes' 'no' 'yes' 'no' 'yes' 'yes' 'yes' 'yes' 'yes'
 'no']


In [20]:
# Converting the Object into into integer by LAbel Encoder
#Converting the String LAbel number into one column at a time 
# weather and temperature
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
x[:,0]=encoder.fit_transform(x[:,0])
x[:,1]=encoder.fit_transform(x[:,1])
y=encoder.fit_transform(y)

In [21]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.4)

In [27]:
#Import Multinimial Naive Bayes Model
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(X_train,y_train)

GaussianNB()

In [28]:
print("Training Accuracy= {}".format(model.score(X_train,y_train)))

Training Accuracy= 0.75


In [29]:
print("Testing Accuracy= {}".format(model.score(X_test,y_test)))

Testing Accuracy= 0.8333333333333334


In [30]:
pred = model.predict(X_test)
print(pred)

[1 1 1 0 0 1]


In [31]:
from sklearn.metrics import classification_report,confusion_matrix
result=confusion_matrix(y_test,pred)

In [32]:
print("Confusion matrix")
print(result)

Confusion matrix
[[2 1]
 [0 3]]


In [33]:
result1=classification_report(y_test,pred)

In [34]:
print("classification_report")
print(result1)

classification_report
              precision    recall  f1-score   support

           0       1.00      0.67      0.80         3
           1       0.75      1.00      0.86         3

    accuracy                           0.83         6
   macro avg       0.88      0.83      0.83         6
weighted avg       0.88      0.83      0.83         6

